#!/bin/bash

npm i markdown-toc-gen

npx markdown-toc-gen update README.md

git config --global user.name "github-actions[bot]"
git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add README.md
git commit -m "Updated Table Of Contents"
git push
