#!/bin/bash

#####################################################
#  Download Specific folders from Github using SVN
#  
#  Orginal Author: Declan Cook
#  Modified by: MarketingPip from github.com/MarketingPipeline
#  Licence: MIT
#####################################################
npm i markdown-toc-gen

npm markdown-toc-gen update README.md

